{
 "title": "GammaGamma Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# **Data Centre Performance Monitor**\n---\nProjektmanagement inkl. Softwareprojekt\n\n\nWintersemester 2022/23\n\n\n*im Auftrag des Öko-Instituts e.V.*\n\n\n<img src=\"https://www.dbu.de/inc/phpThumb/phpThumb.php?src=/media/20052010443246ct.jpg&w=1000\" width=\"300px\"/>"
   }
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 } },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Aktuelle CPU Auslastung",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "betabeta_cpu_auslastung_prozent_sum_by_instance_test_2",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Auslastung pro Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "betabeta_cpu_auslastung_prozent_sum_by_instance_test_2",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Wochenkurve - tagesdurchschn. CPU Auslastung pro Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(betabeta_cpu_auslastung_prozent_sum_by_instance_test_2[24h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Speichersysteme", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Aktuelle Speicherauslastung",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "betabeta_speicherauslastung_terabyte_sum_by_instance_test_1",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Speicherauslastung pro Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "targets": [
    {
     "expr": "betabeta_speicherauslastung_terabyte_sum_by_instance_test_1",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Wochenkurve - tagesdurchschn. Speicherauslastung pro Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(betabeta_speicherauslastung_terabyte_sum_by_instance_test_1[24h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "durchschn. Lese-/Schreib-Volumen in GB pro Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "betabeta_lese_schreib_volumen_gigabyte_average_by_instance_test_1",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Netzwerk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Aktuell übertragene Datenmenge",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "betabeta_uebertragene_datenmenge_gigabyte_sum_by_instance_test_1",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Übertragene Datenmenge pro Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "betabeta_uebertragene_datenmenge_gigabyte_sum_by_instance_test_1",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Wochenkurve - tagesdurchschn. übertragene Datenmenge pro Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(betabeta_uebertragene_datenmenge_gigabyte_sum_by_instance_test_1[24h])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}